[package]
name = "exp004"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
rayon = "1.8"
zip = "0.6"
anyhow = "1.0"
thiserror = "1.0"
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
humansize = "2.1"
chrono = "0.4"
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.10"
criterion = "0.5"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
